apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-manager
spec:
  selector:
    matchLabels:
      app: kafka-manager
      tier: kafka-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-manager
        tier: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: hlebalbau/kafka-manager
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 1024Mi
        env:
        - name: ZK_HOSTS
          value: kfk-cp-zookeeper:9092

        ports:
        - containerPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  labels:
    app: kafka-manager
    tier: kafka-manager
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: LoadBalancer
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 9000
  selector:
    app: kafka-manager
    tier: kafka-manager
