apiVersion: v1
kind: Pod
metadata:
  name: test-client
  namespace: default
spec:
  containers:
  - name: test-client
    image: gcr.io/ccproject-k8s/ccproject:latest
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
