apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-kafka.fullname" . }}
  labels:
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: 9092
      name: broker
      targetPort: 9092
  selector:
    app: {{ template "cp-kafka.name" . }}
    release: {{ .Release.Name }}