apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-control-center.fullname" . }}
  labels:
    app: {{ template "cp-control-center.name" . }}
    chart: {{ template "cp-control-center.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - name: cc-http
      port: {{ .Values.serviceHttpPort }}
      nodePort: {{ .Values.serviceHttpPort }}
  selector:
    app: {{ template "cp-control-center.name" . }}
    release: {{ .Release.Name }}
