apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-kafka
spec:
  selector:
    matchLabels:
      app: json-kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: json-kafka
    spec:
      containers:
      - name: json-kafka
        image: gcr.io/ccproject-k8s/ccproject@sha256:e29baa447a942b706ae8a1db145aba51329c0bdd457beb5750b404c9f0f7476d
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 1024Mi
        args:
          - "--mode"
          - "json-kafka"
          - "--json-port"
          - "5600"
          - "--kafka-server"
          - "kfk-cp-kafka-headless:9092"
          - "--kafka-topic"
          - "main"
          - "--debug"
          - "true"
        ports:
        - containerPort: 5600

---

apiVersion: v1
kind: Service
metadata:
  name: json-kafka
  labels:
    app: json-kafka
spec:

  type: NodePort

  ports:
  - port: 5600
    nodePort: 30000
  selector:
    app: json-kafka
