image: gcr.io/ccproject-k8s/ccproject:latest
debug: true

kafka:
    server: kfk-cp-kafka-headless:9092
    topic: 
        raw: main
        filtered: main-filtered

redis:
    server: redis-master.default.svc.cluster.local
    port: 6379
    key: XGFwZtvUgSzwJuKTGgXWzWTu8kvE78bW
    channel: main

hbase:
    server: hbase-hbase-master:16000
    family: info
    table: Records

jsonToKafka:
    replicas: 3
    service:
        port: 5600
        type: LoadBalancer
    resources:
        requests:
            cpu: 10m
            memory: 50Mi
        limits:
            cpu: 1000m
            memory: 1024Mi

kafkaFilter:
    replicas: 1
    resources:
        requests:
            cpu: 10m
            memory: 50Mi
        limits:
            cpu: 1000m
            memory: 1024Mi

kafkaRedis:
    replicas: 1
    resources:
        requests:
            cpu: 10m
            memory: 50Mi
        limits:
            cpu: 1000m
            memory: 1024Mi

redisHbase:
    replicas: 1
    resources:
        requests:
            cpu: 10m
            memory: 50Mi
        limits:
            cpu: 1000m
            memory: 1024Mi
